# Wait times (in ms)
# Took from doc: https://download.schneider-electric.com/files?p_enDocType=User+guide&p_File_Name=35000789_K06_000_00.pdf&p_Doc_Ref=35000789K01000
from enum import Enum

TBIT = 1 / 9600 * 1000
ICT = 2000
TRET_MIN = 10 * TBIT
TRET_MAX = ICT

TERT_MIN = 150 # TEST

TIMEOUT_SEC = 2 # Time between message sent and received in second

# Special chars
DLE = 0x10
STX = 0x02
ENQ = 0x05
ACK = 0x06

# Category types
TYPE_TSX = 7

# Request codes
MIRROR = 0xFA
IDENTIFICATION = 0x0F
STATUS = 0x31
AVAILABLE_RAM = 0xF5
SEND_MESSAGE = 0xF5
UNSOLICITED_DATA = 0xFC

READ_INTERNAL_BIT = 0x00
READ_SYSTEM_BIT = 0x01
READ_INTERNAL_WORD = 0x04
READ_SYSTEM_WORD = 0x06
READ_CONSTANT_WORD = 0x05
READ_INTERNAL_DWORD = 0x40
READ_CONSTANT_DWORD = 0x41
READ_OBJECTS = 0x36

#Answer codes 

READ_INTERNAL_BIT_ANSWER = 0x30
READ_INTERNAL_WORD_ANSWER = 0x34
READ_INTERNAL_DWORD_ANSWER = 0x70
READ_CONSTANT_DWORD_ANSWER = 0x35
READ_SYSTEM_BIT_ANSWER = 0x31
READ_SYSTEM_WORD_ANSWER = 0x36

#READ_DIGITAL_MODULE_IMAGE = 0x49
READ_IO_CHANNEL = 0x43

WRITE_INTERNAL_BIT = 0x10
WRITE_SYSTEM_BIT = 0x11
WRITE_INTERNAL_WORD = 0x14
WRITE_SYSTEM_WORD = 0x15
WRITE_INTERNAL_DWORD = 0x46
WRITE_OBJECTS = 0x37
WRITE_IO_CHANNEL = 0x48

# Response codes
# For reading requests: response = request code + 0x30
# For mirror request: response = 0xFB
# For writing requests: response = 0xFE
RESPONSE_CODES = {
    MIRROR: 0xFB,
    IDENTIFICATION: 0x3F,
    AVAILABLE_RAM: [0xF5, 0x77],
    SEND_MESSAGE: 0xFE,
    STATUS: 0x61,
    WRITE_INTERNAL_BIT: 0xFE,
    WRITE_SYSTEM_BIT: 0xFE,
    WRITE_INTERNAL_WORD: 0xFE,
    WRITE_SYSTEM_WORD: 0xFE,
    WRITE_INTERNAL_DWORD: 0xFE,
    WRITE_OBJECTS: 0xFE,
}

class READ_OBJECT_ADDRESSES(Enum):
    AXIS_POSITION_REFERENCE = 0x80
    AXIS_MEASUREMENT = 0x81
    AXIS_DAT1_VALUES = 0x82
    AXIS_DAT2_VALUES = 0x83
    AXIS_DAT3_VALUES = 0x84
    MINIMUM_DYNAMIC_AXIS_TRAVEL = 0x85
    MAXIMUM_DYNAMIC_AXIS_TRAVEL = 0x86
    INCLINED_AXIS_ANGULAR_VALUE = 0x87
    MACHINE_ZERO_POINT = 0x88
    MINIMUM_STATIC_TRAVEL = 0x89
    MAXIMUM_STATIC_TRAVEL = 0x8A
    CURRENT_CORRECTIONS_SLAVE_AXIS = 0x8B
    AXIS_POSITION_REFERENCE_AXISWISE = 0x8C
    AXIS_MEASUREMENT_AXISWISE = 0x8D
    DRIVEN_AXES = 0x8F
    MEASURED_SPINDLE_SPEED_SETTING = 0x90
    MEASURED_SPINDLE_REFERENCE_POSITION = 0x91
    TOOL_CORRECTIONS = 0x92
    H_VARIABLE_DYNAMIC_CORRECTORS = 0x93
    INTERPOLATION_STATUS = 0x94
    HOMING_NOT_DONE_ON_AXES = 0x95
    LOCAL_DATA_PARAMETERS_E = 0x96
    MASTER_AXIS_REFERENCE_POSITION_INTERAXIS_CALIBRATION = 0x97
    SLAVE_AXIS_CORRECTION_INTERAXIS_CALIBRATION = 0x98
    PROGRAMME_STATUS = 0x99
    BLOCK_END_DIMENSIONS = 0x9D
    MODE_SELECTION = 0xB4
    CURRENT_PROGRAMME_NUMBER = 0xB5
    DATA_TRANSMITTED_TO_PROGRAMME_BEING_EXECUTED = 0xE0
    ACKNOWLEDGEMENT_OF_BLOCKING_MESSAGE = 0xE2 #$11 or $22

# READ_OBJECT_ADDRESSES = {
#     AXIS_POSITION_REFERENCE: 0x80,
#     AXIS_MEASUREMENT: 0x81,
#
# }